// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYcOP9J6VC13Mn0syM64opZp40RqjkV7s',
    appId: '1:319070808679:web:5f8b3d40bf3580561302c2',
    messagingSenderId: '319070808679',
    projectId: 'iotproject-4ae18',
    authDomain: 'iotproject-4ae18.firebaseapp.com',
    databaseURL: 'https://iotproject-4ae18-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotproject-4ae18.appspot.com',
    measurementId: 'G-JF134QQV19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMtbvRAejpkXqfWPba7LMpZcJTRCx1Svo',
    appId: '1:319070808679:android:b0ca1fc09cb4f1bf1302c2',
    messagingSenderId: '319070808679',
    projectId: 'iotproject-4ae18',
    databaseURL: 'https://iotproject-4ae18-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotproject-4ae18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMmmTfXaP3hHjEo1s8aGxqGfUUbZracT4',
    appId: '1:319070808679:ios:f97743207396abe01302c2',
    messagingSenderId: '319070808679',
    projectId: 'iotproject-4ae18',
    databaseURL: 'https://iotproject-4ae18-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotproject-4ae18.appspot.com',
    iosBundleId: 'com.example.oldiot',
  );
}
